gpu: 'cuda'
# gpu: 'cpu'
epochs: 400
optimizer: "adamw"
lr: 1e-4
min_lr: 1e-7
weight_decay: 0.0
warmup_epochs: 10
patience_epochs: 0
load_model: "runs/pretrain_cloud_optimade"
# load_model: None
resume_from_checkpoint: False
log_every_n_steps: 50
fold_num: 1
LLRD: False
freeze_epoch: 0
test_MAE/MAD: True

max_norm: 5.0
mu: 1500.0
scale: 1200.0
task: "cv"

model:
  max_position_embeddings: 64
  num_attention_heads: 12
  num_hidden_layers: 12
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  dropout: 0.1
  num_layers: 3

dataset:  
  dataset_name: 'cv_debye'
  batch_size: 128
  num_workers: 2
  vocab_path: 'tokenizer_cloud_optimade'
  blocksize: 64
  seed: 0
  valid_size: 0.25