gpu: 'cuda'
# gpu: 'cpu'
epochs: 400
optimizer: "adamw"
lr: 1e-4
min_lr: 1e-7
weight_decay: 0.0
warmup_epochs: 10
patience_epochs: 0
load_model: "/home/changwex/scratch/ML_SSE/runs/pretrain_cloud_optimade_6M_new"
# load_model: None
resume_from_checkpoint: False
log_every_n_steps: 50
fold_num: 1
LLRD: False
freeze_epoch: 0
test_MAE/MAD: True

# save_path: 'cv_sg_cloud_debye_u_new_error_0.csv'

max_norm: 5.0
mu: 1500.0
scale: 1200.0
task: "cv"

# weight_cv: 0.5
# weight_u: 0.5

model:
  # # Bert
  # max_position_embeddings: 64
  # num_attention_heads: 12
  # num_hidden_layers: 12
  # hidden_dropout_prob: 0.1
  # attention_probs_dropout_prob: 0.1
  # dropout: 0.1
  # num_layers: 3

  # # Multi-modal
  # structure_net_params:
  #   # orig_atom_fea_len:
  #   # nbr_fea_len:
  #   atom_fea_len: 64
  #   n_conv: 3
  #   h_fea_len: 128
  #   n_h: 1
  #   classification: False
  # composition_net_params:
  #   robust: True
  #   task_dict: ['regression']
  #   # elem_emb_len: 
  #   elem_fea_len: 128
  #   n_graph: 3
  #   elem_heads: 3
  # weight_net_params:
  #   input_dim: 128
  #   output_dim: 1
  #   hidden_layer_dims: [128,64]
  # output_net_params:
  #   input_dim: 128
  #   output_dim: 1
  #   hidden_layer_dims: [128,64]

  # # Roost
  # robust: False
  # task_dict: ['regression']
  # # elem_emb_len: 
  # elem_fea_len: 128
  # n_graph: 3
  # elem_heads: 3

  # CGCNN
  # orig_atom_fea_len:
  # nbr_fea_len:
  atom_fea_len: 128
  n_conv: 3
  h_fea_len: 256
  n_h: 1
  classification: False

dataset:  
  # dataset_name: 'matbench_log_gvrh'
  # dataset_name: 'matbench_mp_e_form'
  # dataset_name: 'data/cond/slices'
  # dataset_name: 'matbench_jdft2d'
  # dataset_name: 'matbench_phonons'
  # dataset_name: 'matbench_dielectric'
  # dataset_name: 'matbench_log_kvrh'
  # dataset_name: 'matbench_perovskites'
  # dataset_name: 'matbench_mp_gap'
  # dataset_name: './data/cond/gen'
  # dataset_name: 'unconvbench_defected'
  # dataset_name: 'cloud_sg_cv_u'
  dataset_name: 'cgcnn_sg_cv_debye'
  # dataset_name: 'cloud_sg_internal_energy_debye'
  # dataset_name: "cloud_sg_u_new"
  # dataset_name: 'cloud_cond_new'
  batch_size: 128
  num_workers: 2
  # vocab_path: 'tokenizer_cloud_optimade'
  # blocksize: 64
  # map_path: './data/gen_map_large.json'
  seed: 0
  valid_size: 0.25