gpu: 'cuda'
# gpu: 'cpu'
epochs: 200
optimizer: "adamw"
lr: 1e-4
min_lr: 1e-7
weight_decay: 0.0
warmup_epochs: 2
patience_epochs: 3
load_model: "runs/pretrain_cloud_optimade"
resume_from_checkpoint: False
log_every_n_steps: 50
LLRD: False
freeze_epoch: 10
save_path: "cloud_mb_discovery"

model:
  # Bert
  max_position_embeddings: 64
  num_attention_heads: 12
  num_hidden_layers: 12
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  dropout: 0.1
  num_layers: 3

dataset:
  dataset_name: 'data/mp_cloud.csv'
  batch_size: 1024
  num_workers: 2
  vocab_path: './tokenizer_cloud_optimade'
  blocksize: 64
  seed: 42
  valid_size: 0.05
  